-- MySQL Script generated by MySQL Workbench
-- Tue Jan 22 19:06:24 2019
-- Model: Shack Locations    Version: 1.2.7
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema ShackLocations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `#__focalpoint_legends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__focalpoint_legends` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ordering` INT(11) NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '1',
  `title` VARCHAR(150) NOT NULL,
  `alias` VARCHAR(250) NOT NULL,
  `subtitle` VARCHAR(300) NOT NULL,
  `checked_out` INT(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `#__focalpoint_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__focalpoint_locations` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state` TINYINT(1) NOT NULL DEFAULT '1',
  `ordering` INT(11) NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `map_id` INT(11) NOT NULL,
  `type` INT(11) NOT NULL,
  `othertypes` VARCHAR(250) NOT NULL,
  `alias` VARCHAR(250) NOT NULL,
  `description` TEXT NOT NULL,
  `fulldescription` TEXT NOT NULL,
  `image` TEXT NOT NULL,
  `linktype` TINYINT(1) NOT NULL DEFAULT '0',
  `altlink` VARCHAR(300) NOT NULL,
  `maplinkid` INT(11) NOT NULL,
  `menulink` VARCHAR(300) NOT NULL,
  `address` VARCHAR(300) NOT NULL,
  `geoaddress` VARCHAR(300) NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  `latitude` DECIMAL(10,6) NOT NULL,
  `longitude` DECIMAL(10,6) NOT NULL,
  `checked_out` INT(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `marker` VARCHAR(255) NOT NULL,
  `keylocation` VARCHAR(255) NOT NULL,
  `includesubcats` VARCHAR(255) NOT NULL,
  `customfieldsdata` TEXT NOT NULL,
  `created_by` INT(11) NOT NULL,
  `params` VARCHAR(255) NOT NULL,
  `metadata` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `#__focalpoint_locationtypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__focalpoint_locationtypes` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ordering` INT(11) NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '1',
  `title` VARCHAR(150) NOT NULL,
  `alias` VARCHAR(250) NOT NULL,
  `description` TEXT NOT NULL,
  `marker` VARCHAR(255) NOT NULL,
  `legend` INT(11) NOT NULL,
  `checked_out` INT(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `customfields` TEXT NOT NULL,
  `created_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `#__focalpoint_location_type_xref`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__focalpoint_location_type_xref` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `location_id` INT(11) NOT NULL,
  `locationtype_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `#__focalpoint_maps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `#__focalpoint_maps` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ordering` INT(11) NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '1',
  `title` VARCHAR(150) NOT NULL,
  `alias` VARCHAR(250) NOT NULL,
  `text` TEXT NOT NULL,
  `tabsdata` TEXT NOT NULL,
  `checked_out` INT(11) NOT NULL,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `centerpoint` VARCHAR(300) NOT NULL,
  `latitude` DECIMAL(10,6) NOT NULL,
  `longitude` DECIMAL(10,6) NOT NULL,
  `kmlfile` VARCHAR(255) NOT NULL,
  `created_by` INT(11) NOT NULL,
  `metadata` TEXT NOT NULL,
  `params` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
